// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_uniw5nWeLXdUTcaadXtZY_BmNiBprA',
    appId: '1:485714063563:web:ff4232a17747a718a7ab4e',
    messagingSenderId: '485714063563',
    projectId: 'shadow-slave-rpg',
    authDomain: 'shadow-slave-rpg.firebaseapp.com',
    storageBucket: 'shadow-slave-rpg.firebasestorage.app',
    measurementId: 'G-598LMSSPFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsZChGl5JmNTFmPPc0r604EdUW3CqXkk',
    appId: '1:485714063563:android:83d8c04f6ebf9782a7ab4e',
    messagingSenderId: '485714063563',
    projectId: 'shadow-slave-rpg',
    storageBucket: 'shadow-slave-rpg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkt6vPE_6JR_VulLmXjVmFRe98Pm2WUXk',
    appId: '1:485714063563:ios:23746e7b6362d135a7ab4e',
    messagingSenderId: '485714063563',
    projectId: 'shadow-slave-rpg',
    storageBucket: 'shadow-slave-rpg.firebasestorage.app',
    iosBundleId: 'com.example.shadowSlaveRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkt6vPE_6JR_VulLmXjVmFRe98Pm2WUXk',
    appId: '1:485714063563:ios:23746e7b6362d135a7ab4e',
    messagingSenderId: '485714063563',
    projectId: 'shadow-slave-rpg',
    storageBucket: 'shadow-slave-rpg.firebasestorage.app',
    iosBundleId: 'com.example.shadowSlaveRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_uniw5nWeLXdUTcaadXtZY_BmNiBprA',
    appId: '1:485714063563:web:578975054d5e1d4fa7ab4e',
    messagingSenderId: '485714063563',
    projectId: 'shadow-slave-rpg',
    authDomain: 'shadow-slave-rpg.firebaseapp.com',
    storageBucket: 'shadow-slave-rpg.firebasestorage.app',
    measurementId: 'G-2DQSF91LJ6',
  );
}
